linters:
  enable:
    - dogsled
    - dupl
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - stylecheck
    - unconvert
    - unparam
    - whitespace
linters-settings:
  stylecheck:
    go: "1.16"
    checks:
      - all
      - '-ST1003' # Poorly chosen identifier
